### ISSUE TITLE
IndexError: take_ownership() in updateactions.py

### ISSUE THREAD

**Issue by d-omkar0** [rafaelh/update-kali#4]
[i] 05:51:48 - Checking ruby gems                                                                  
Traceback (most recent call last):                                                                 
  File "/opt/update-kali/./update-kali", line 113, in <module>                                     
    main()                                                                                         
  File "/opt/update-kali/./update-kali", line 76, in main                                          
    take_ownership(external_tools_directory)                                                       
  File "/opt/update-kali/updateactions.py", line 22, in take_ownership                             
    username = os.path.expanduser("~").split('/')[2]                                               
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^                                               
IndexError: list index out of range

**Comment by rafaelh** [comment]
Looks like something in your environment is causing the script to misbehave. Most linux installations expect users to be in /home/<username>, as does this code, and your environment is returning something that is different (are you running this on a mac for example?). I'd recommend going into a python interpreter and running:
```
import os
user = os.path.expanduser("~")
print(user)
```
That should let you know what is going wrong, as the intent of that line is to break the user path down into just the username, for insertion into other commands. The way this script is programed is quite brittle, as it should really be using methods from the python `os` library throughout the script, rather than assembling shell commands on the fly, but it was quick to develop that way. Feel free to submit a pull request if you'd like to improve it.
